# Generated by Django 3.1.2 on 2020-11-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201105_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('pod', 'Pay On Delivery'), ('paypal', 'PayPal'), ('google', 'Google Pay'), ('apple', 'Apple Pay')], default='pod', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_charge',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
