# Generated by Django 3.1.3 on 2020-11-04 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_booking_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
    ]
